<?php

namespace Zowesoft\LaravelPrisma\Services\LaravelMode;

/**
 * MigrationFileWriter
 *
 * Assembles a standard Laravel PHP migration class from an array of
 * Schema Builder code blocks (generated by SqlToSchemaBuilder) and writes
 * it to the database/migrations directory.
 */
class MigrationFileWriter
{
    /**
     * Write a Laravel migration file.
     *
     * @param  string   $name       The human migration name, e.g. "add_bio_to_users_table"
     * @param  string[] $upBlocks   PHP code blocks for the up() method
     * @param  string   $targetDir  Absolute path to the database/migrations directory
     * @return string               Absolute path to the written file
     * @throws \RuntimeException    If a migration with this name already exists
     */
    public function write(string $name, array $upBlocks, string $targetDir): string
    {
        $existing = $this->findExisting($name, $targetDir);
        if ($existing !== null) {
            throw new \RuntimeException(
                "A migration named '{$name}' already exists: " . basename($existing)
            );
        }

        $className = $this->toClassName($name);
        $filename  = $this->buildFilename($name, $targetDir);
        $upBody    = $this->indentBlocks($upBlocks);
        $needsDb   = $this->blocksNeedDbFacade($upBlocks);

        $stub = $this->buildStub($className, $upBody, $needsDb);

        if (! is_dir($targetDir)) {
            mkdir($targetDir, 0755, true);
        }

        file_put_contents($filename, $stub);

        return $filename;
    }

    /**
     * Check whether a migration file with the given name already exists
     * in the target directory (regardless of the timestamp prefix).
     *
     * @return string|null  The full path of the existing file, or null if not found
     */
    public function findExisting(string $name, string $targetDir): ?string
    {
        if (! is_dir($targetDir)) {
            return null;
        }

        $matches = glob($targetDir . DIRECTORY_SEPARATOR . "*_{$name}.php");

        return ! empty($matches) ? $matches[0] : null;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Stub builder
    // ─────────────────────────────────────────────────────────────────────────

    private function buildStub(string $className, string $upBody, bool $needsDb): string
    {
        $dbImport = $needsDb ? "\nuse Illuminate\\Support\\Facades\\DB;" : '';

        return <<<PHP
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;{$dbImport}

return new class extends Migration
{
    /**
     * Run the migrations.
     * Generated by laravel-prisma — do not edit manually.
     */
    public function up(): void
    {
        {$upBody}
    }

    /**
     * Reverse the migrations.
     * Note: Down migrations are not auto-generated by laravel-prisma.
     * Implement manually if rollback support is needed.
     */
    public function down(): void
    {
        // Schema::dropIfExists('your_table');
    }
};
PHP;
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Helpers
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Convert a snake_case migration name to a PascalCase class name.
     * e.g. "add_bio_to_users_table" → "AddBioToUsersTable"
     */
    private function toClassName(string $name): string
    {
        return str_replace(' ', '', ucwords(str_replace('_', ' ', $name)));
    }

    /**
     * Build the full file path using a Laravel-style timestamp prefix.
     * Avoids collisions by appending a microsecond-based suffix.
     */
    private function buildFilename(string $name, string $targetDir): string
    {
        $timestamp = date('Y_m_d_His');

        // Prevent collisions if multiple migrations are generated at once
        $existing = glob($targetDir . DIRECTORY_SEPARATOR . "*_{$name}.php");
        if (! empty($existing)) {
            $timestamp = date('Y_m_d_') . str_pad((int)(microtime(true) * 100) % 1000000, 6, '0', STR_PAD_LEFT);
        }

        return $targetDir . DIRECTORY_SEPARATOR . "{$timestamp}_{$name}.php";
    }

    /**
     * Indent each code block by 8 spaces (inside the up() method body)
     * and join them with blank lines.
     */
    private function indentBlocks(array $blocks): string
    {
        $indented = array_map(function (string $block) {
            // Each line inside the block gets 8 spaces of indentation
            $lines = explode("\n", $block);
            $lines = array_map(fn($l) => strlen(trim($l)) > 0 ? '        ' . $l : '', $lines);
            return implode("\n", $lines);
        }, $blocks);

        return implode("\n\n        ", array_map('trim', $indented));
    }

    /**
     * Check if any block uses DB::unprepared(), to know whether we need
     * to import the DB facade.
     */
    private function blocksNeedDbFacade(array $blocks): bool
    {
        foreach ($blocks as $block) {
            if (str_contains($block, 'DB::unprepared')) {
                return true;
            }
        }
        return false;
    }
}
